name: farmers
on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    # Remove container to avoid glibc issues
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install dvc
      
      - name: Setup CML
        uses: iterative/setup-cml@v1
      
      - name: Run DVC pipeline and generate report
        env:
          REPO_TOKEN: ${{ secrets.PAT_TOKEN }}  # Use your PAT instead of GITHUB_TOKEN
        run: |
          # Run the DVC pipeline
          dvc repro
          
          # Create report with metrics
          git fetch --prune
          dvc metrics diff master > metrics_diff.txt || echo "No metrics diff available" > metrics_diff.txt
          
          echo "## Model Metrics" > report.md
          cat metrics_diff.txt >> report.md
          
          # Add figure to the report
          echo -e "\n## Validating results by region" >> report.md
          echo "![](./by_region.png)" >> report.md
          
          # Use updated CML command to create comment
          cml comment create report.md
